### ISSUE TITLE
Document how to resolve `Cannot find module 'react/jsx-runtime'` error in VS Code

### ISSUE THREAD

**Issue by netr0m** [equinor/template-fastapi-react#134]
If you come across the following error;
```
Cannot find module 'react/jsx-runtime' or its corresponding type declarations.ts(2307)
```
then you need to select the proper typescript version to use the workspace version:
1. Press `ctrl+shift+p` in a TypeScript file
2. Choose "Select TypeScript Version"
3. Pick "Use Workspace Version"

**Comment by sebastianvitterso** [comment]
Is this still needed, though? After https://github.com/equinor/template-fastapi-react/pull/119, the version should be selected by default whenever the user opens the repository. 

I just tested now, by cloning the repo into a new folder, and upon initial load of a `tsx`-file, I was presented with this message: 
![image](https://user-images.githubusercontent.com/37065184/201308296-ee2c8198-2ba1-4213-afdf-5a18cd59e3e3.png)


Upon clicking `Allow`, it looks like so:
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/37065184/201308422-9ce29402-3c7d-4c8b-bac1-f339482041eb.png">

**Comment by sebastianvitterso** [comment]
@netr0m There's a tiny chapter in the docs called [Yarn PnP in VSCode](https://equinor.github.io/template-fastapi-react/docs/contribute/development-guide/setup#yarn-pnp-in-vscode). That's the same thing, yes? 

<img width="898" alt="image" src="https://user-images.githubusercontent.com/37065184/201612330-2ac612b1-f6c7-4bd9-b036-17c4df2f7324.png">

I suppose I can update it to point to the right place, and recommend using the `CTRL+SHIFT+P` version.

**Comment by olavis** [comment]
> @netr0m There's a tiny chapter in the docs called [Yarn PnP in VSCode](https://equinor.github.io/template-fastapi-react/docs/contribute/development-guide/setup#yarn-pnp-in-vscode). That's the same thing, yes?
> 
> <img alt="image" width="898" src="https://user-images.githubusercontent.com/37065184/201612330-2ac612b1-f6c7-4bd9-b036-17c4df2f7324.png">
> 
> I suppose I can update it to point to the right place, and recommend using the `CTRL+SHIFT+P` version.

Not quite the same. I've sometimes experienced that I had to try this as well, when not even the steps @netr0m mentioned worked out. Sometimes the workspace version won't appear on the list with `cmd+shift+P`, but this solves it.
