### ISSUE TITLE
Go through documentation

### ISSUE THREAD

**Issue by eoaksnes** [equinor/template-fastapi-react#56]
How to best structure the [documentation](  https://equinor.github.io/template-fastapi-react).

**Comment by eoaksnes** [comment]
![image](https://user-images.githubusercontent.com/1190419/185590515-04b33cbf-bac6-4251-81c1-0c9cebade258.png)

**Comment by KristianKjerstad** [comment]
see also https://github.com/equinor/template-fastapi-react/issues/56
