### ISSUE TITLE
Remove version prefix in API url

### ISSUE THREAD

**Issue by KristianKjerstad** [equinor/template-fastapi-react#84]
#### Describe Problem
Putting the version in the API URL is not recommended by Equinor API guidelines.

#### Suggest Solution
Remove version prefix in the API url: https://github.com/equinor/template-fastapi-react/blob/main/api/src/app.py#L16

#### Additional Details
There are better ways to keep track of versions... For example Github tags

**Comment by jorgenengelsen** [comment]
Done!
